version: "3"
services:
  app:
    container_name: "python_machine_leaning"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_machine_learning
    volumes:
      - $PWD:/home/DeepLearning
    tty: true

